version: '3.1'
services:
  stats-server:
    build: ./stats/server
    restart: on-failure
    container_name: ewm-stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
      TZ: Europe/Moscow

  stats-db:
    image: postgres:14-alpine
    restart: on-failure
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stats_db

  ewm-service:
    build: ./main
    restart: on-failure
    container_name: ewm-main
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm_db
      TZ: Europe/Moscow

  ewm-db:
    image: postgres:14-alpine
    restart: on-failure
    container_name: ewm-main-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ewm_db
